#!/bin/bash
#SBATCH -J lab1_hj_gpu
#SBATCH --partition ice-gpu,coc-gpu
#SBATCH -C "intel&core40&gpu-v100"
#SBATCH -N 1 --ntasks-per-node=8
#SBATCH --gres=gpu:1
#SBATCH --exclusive
#SBATCH --mem=0
#SBATCH --time=00:20:00
#SBATCH --error=job.%J.err
#SBATCH --output=job.%J.out

#Setup Environment
cd $SLURM_SUBMIT_DIR
source pace_env.sh

make clean metrics IMPL=hj
./metrics -t 50 -n 10000000 -o results_hj_cuda.json

exit 0
